[features]
seeds = false
skip-lint = false
[programs.localnet]
cricket_clash_gems = "4iZPpi28h4K5MpcNxjpwrJdQqgTUQmtiHM24zbagsheX"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/adityakasibhatla/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
